#!/usr/bin/env python3
"""Generate postgis/init/06-geo-thailand.sql from TH_PROVINCE.gpkg.

geo_thailand is the full-resolution province boundary table used for
service-area checks (ProvinceService / /plots/nav, /plots/info) — distinct
from geo_province, which holds simplified geometry for map navigation and
has no p_code column to match against REGION_CONFIG.

The source gpkg is un-dissolved (a province's boundary is split across many
polygon parts sharing the same P_CODE), so this script dissolves by P_CODE
in the source projected CRS (EPSG:32647, metres — more robust for topology
than dissolving in degrees), applies a small topology-preserving simplify
(SIMPLIFY_TOLERANCE_M) to tame the raw vertex count (~6.5M vertices / 239MB
undissolved), then reprojects the result to EPSG:4326 to match the storage
convention of the other geo_* tables.

Run inside an env with geopandas installed (the backend container has one):

    docker exec -i keptcarbon-backend-1 python3 \
        < postgis/gen_geo_thailand_sql.py > postgis/init/06-geo-thailand.sql
"""
import sys

import geopandas as gpd
from shapely import wkt as shapely_wkt
from shapely.geometry import MultiPolygon

# Decimal places kept in the output WKT. 6 places is ~0.11m at Thailand's
# latitude -- far finer than the source survey accuracy, but keeps file
# size sane (the raw dissolved geometry is ~6.5M vertices / 239MB at full
# float precision).
COORD_PRECISION = 6

# Douglas-Peucker tolerance in metres, applied in EPSG:32647 (preserve_topology=True
# so provinces never gain self-intersections or gaps). 3m is imperceptible at
# province scale and far below source survey accuracy, but cuts vertex count
# drastically -- this is a much lighter simplification than geo_province's
# map-display geometry, kept precise enough for service-area point checks.
SIMPLIFY_TOLERANCE_M = 3

GPKG_PATH = "app/data/shp/TH_PROVINCE.gpkg"  # relative to backend container cwd


def esc(val):
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def to_multipolygon(geom):
    if geom.geom_type == "Polygon":
        return MultiPolygon([geom])
    return geom


def main():
    gdf = gpd.read_file(GPKG_PATH)

    dissolved = gdf.dissolve(by="P_CODE", aggfunc="first").reset_index()
    dissolved["geometry"] = dissolved["geometry"].simplify(
        SIMPLIFY_TOLERANCE_M, preserve_topology=True
    )
    dissolved = dissolved.to_crs("EPSG:4326")
    dissolved["geometry"] = dissolved["geometry"].apply(to_multipolygon)
    dissolved = dissolved.sort_values("PROV_CODE")

    lines = [
        "-- " + "=" * 72,
        "-- geo_thailand: full-resolution province boundaries (service-area checks)",
        "-- Source: TH_PROVINCE.gpkg, dissolved by P_CODE, EPSG:32647 -> EPSG:4326",
        "-- Generated by postgis/gen_geo_thailand_sql.py -- do not edit by hand",
        "-- " + "=" * 72,
        "",
        "CREATE TABLE public.geo_thailand (",
        "    id SERIAL PRIMARY KEY,",
        "    p_code text NOT NULL,",
        "    prov_code text NOT NULL,",
        "    prov_name_th text,",
        "    prov_name_en text,",
        "    region text,",
        "    geom geometry(MultiPolygon,4326)",
        ");",
        "",
        "INSERT INTO public.geo_thailand (p_code, prov_code, prov_name_th, prov_name_en, region, geom)",
        "VALUES",
    ]

    rows = []
    for _, r in dissolved.iterrows():
        wkt = shapely_wkt.dumps(r.geometry, rounding_precision=COORD_PRECISION)
        geom_sql = f"ST_SetSRID('{wkt}'::geometry, 4326)"
        rows.append(
            f"  ({esc(r['P_CODE'])}, {esc(r['PROV_CODE'])}, {esc(r['PROV_NAM_T'])}, "
            f"{esc(r['PROV_NAM_E'])}, {esc(r['REGION'])}, {geom_sql})"
        )
    lines.append(",\n".join(rows) + ";")
    lines.append("")

    lines += [
        "CREATE UNIQUE INDEX geo_thailand_p_code_idx ON public.geo_thailand (p_code);",
        "CREATE INDEX geo_thailand_geom_idx ON public.geo_thailand USING gist (geom);",
        "",
    ]

    sys.stdout.write("\n".join(lines) + "\n")
    n_vertices = sum(
        sum(len(p.exterior.coords) + sum(len(i.coords) for i in p.interiors) for p in g.geoms)
        for g in dissolved["geometry"]
    )
    print(
        f"-- {len(dissolved)} provinces dissolved from {len(gdf)} source parts, "
        f"{n_vertices} vertices after {SIMPLIFY_TOLERANCE_M}m simplify",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()