#!/usr/bin/env python3
"""Generate postgis/init/14-biomass-profile-data.sql from the source CSVs
under backend/app/data/lookup_tables/.

tbl_biomass_profile (postgis/init/05-tbl-biomass-profile.sql) replaces the
flat-CSV lookup CarbonService.generate_carbon_profile used pre-refactor
(commit a28cab2), but that commit deleted the CSVs and created the table
schema without ever loading data into it -- this script is the missing load
step.

Two source-CSV shapes exist depending on allometry (both sum to Biomass_Est,
verified against row 0 of every file):
  - hytonen:    Age,DBH_Est,Leaf,LeaflessAGB,StumpRoot,Biomass_Est,CI,Biomass_CI_Lower,Biomass_CI_Upper
                agb = Leaf + LeaflessAGB, bgb = StumpRoot
  - chiarawipa: Age,DBH_Est,Stem,Branch,Leaf,Root,Biomass_Est,CI,Biomass_CI_Lower,Biomass_CI_Upper
                agb = Stem + Branch + Leaf, bgb = Root

Only whole-year Age rows are kept -- most files are quarter-year steps
(0, 0.25, 0.5, ...) but tbl_biomass_profile.age is INTEGER by design (see
that file's header comment); cubic_poly's CSVs are already yearly-only.

Run (no extra deps beyond the stdlib):

    python3 postgis/gen_biomass_profile_sql.py > postgis/init/14-biomass-profile-data.sql
"""
import csv
import sys
from pathlib import Path

P_CODE = "RAY"
CLONE = "RRIM 600"
LOOKUP_DIR = Path(__file__).resolve().parent.parent / "backend" / "app" / "data" / "lookup_tables"

# filename growth-model segment -> (allometry segment, allometry column, AGB cols, BGB cols)
FILES = [
    ("chapman_richards", "chiarawipa", "chiarawipa_2012", ("Stem", "Branch", "Leaf"), ("Root",)),
    ("chapman_richards", "hytonen", "hytonen_2018", ("Leaf", "LeaflessAGB"), ("StumpRoot",)),
    ("cubic_poly", "chiarawipa", "chiarawipa_2012", ("Stem", "Branch", "Leaf"), ("Root",)),
    ("cubic_poly", "hytonen", "hytonen_2018", ("Leaf", "LeaflessAGB"), ("StumpRoot",)),
    ("gompertz", "chiarawipa", "chiarawipa_2012", ("Stem", "Branch", "Leaf"), ("Root",)),
    ("gompertz", "hytonen", "hytonen_2018", ("Leaf", "LeaflessAGB"), ("StumpRoot",)),
    ("schumacher", "chiarawipa", "chiarawipa_2012", ("Stem", "Branch", "Leaf"), ("Root",)),
    ("schumacher", "hytonen", "hytonen_2018", ("Leaf", "LeaflessAGB"), ("StumpRoot",)),
    ("weibull", "chiarawipa", "chiarawipa_2012", ("Stem", "Branch", "Leaf"), ("Root",)),
    ("weibull", "hytonen", "hytonen_2018", ("Leaf", "LeaflessAGB"), ("StumpRoot",)),
]


def esc(val):
    return "'" + str(val).replace("'", "''") + "'"


def main():
    lines = [
        "-- " + "=" * 76,
        "-- tbl_biomass_profile data: per-age biomass lookup rows (p_code=RAY, clone='RRIM 600')",
        "-- Source: backend/app/data/lookup_tables/rrim600_*_rayong.csv",
        "-- Generated by postgis/gen_biomass_profile_sql.py -- do not edit by hand",
        "-- " + "=" * 76,
        "",
        "INSERT INTO tbl_biomass_profile",
        "  (p_code, clone, growth_model, allometry, age, dbh_est, agb, bgb, biomass_est, ci, biomass_ci_lower, biomass_ci_upper)",
        "VALUES",
    ]

    rows = []
    total = 0
    for growth_model, allometry_file, allometry_db, agb_cols, bgb_cols in FILES:
        csv_path = LOOKUP_DIR / f"rrim600_{growth_model}_{allometry_file}_rayong.csv"
        with open(csv_path, newline="") as f:
            for r in csv.DictReader(f):
                age = float(r["Age"])
                if age != int(age):
                    continue  # quarter-year step, table stores whole years only
                agb = sum(float(r[c]) for c in agb_cols)
                bgb = sum(float(r[c]) for c in bgb_cols)
                rows.append(
                    f"  ({esc(P_CODE)}, {esc(CLONE)}, {esc(growth_model)}, {esc(allometry_db)}, "
                    f"{int(age)}, {r['DBH_Est']}, {agb}, {bgb}, {r['Biomass_Est']}, {r['CI']}, "
                    f"{r['Biomass_CI_Lower']}, {r['Biomass_CI_Upper']})"
                )
                total += 1

    lines.append(",\n".join(rows) + ";")
    lines.append("")
    sys.stdout.write("\n".join(lines) + "\n")
    print(f"-- {total} biomass profile rows across {len(FILES)} (growth_model, allometry) combinations", file=sys.stderr)


if __name__ == "__main__":
    main()
