#!/usr/bin/env python3
"""Generate postgis/init/12-geo-landuse.sql from LU_RYG_2567.gpkg.

geo_landuse holds the land-use classification polygons that
LanduseService.find_rubber_cultivation_area / find_lu_class_area currently
loads per-province from REGION_CONFIG[p_code]["lu_vector"] via geopandas.
Unlike geo_thailand, rows are NOT dissolved -- each source feature is a
meaningful individual land-use parcel, and the service clips + dissolves by
a request-time-derived group key (LUL1_CODE, falling back to the finer
LU_CODE for agriculture) against whatever polygon the user drew, so the
raw per-feature rows must be preserved here.

Area columns (Shape_Area, Area_Sqm, Area_Rai) are intentionally dropped --
the service always recomputes area itself (UTM meters, per request), so a
stored area would just be dead weight duplicating the geometry.

p_code is injected as a constant here (REGION_CONFIG only has "RAY" today)
so the table can hold multiple provinces later, mirroring geo_thailand.
lu_year is likewise injected as a constant, taken from the source filename
("_2567" = Buddhist-Era year the LU dataset was produced) -- (p_code, lu_year)
together identify a specific ingested dataset, which is how the planned R&D
data-ingestion feature will add new vintages without overwriting old ones.

LU_ID_L1/L2/L3 (the source gpkg's numeric land-use ID codes) are dropped --
no application code reads them (LanduseService groups by LUL1_CODE, falling
back to LU_CODE, for its area calculations), so they're dead weight. See
migration 013_drop_geo_landuse_lu_id_columns.sql for the same cleanup
applied to an already-seeded database.

Run inside an env with geopandas installed (the backend container has one):

    docker exec -i keptcarbon-backend-1 python3 \
        < postgis/gen_geo_landuse_sql.py > postgis/init/12-geo-landuse.sql
"""
import sys

import geopandas as gpd
import shapely
from shapely import wkt as shapely_wkt
from shapely.geometry import MultiPolygon

P_CODE = "RAY"
LU_YEAR = 2567  # Buddhist Era, matches the "LU_RYG_2567.gpkg" filename convention
GPKG_PATH = "app/data/shp/LU/LU_RYG_2567.gpkg"  # relative to backend container cwd

# Decimal places kept in the output WKT -- see gen_geo_thailand_sql.py for
# the same rationale (~0.11m precision, far finer than source survey
# accuracy, keeps file size sane).
COORD_PRECISION = 6
PRECISION_GRID = 10 ** (-COORD_PRECISION)

# The source geometry is 100% valid at full precision, but naively rounding
# WKT to COORD_PRECISION decimals afterwards collapses near-coincident
# vertices and introduces self-intersections (measured: 92/65136 rows).
# shapely.set_precision(..., mode="valid_output") snaps to the same grid AND
# repairs topology in one step, so every row stays a clean MultiPolygon
# (measured: 0 invalid, max area drift 1.3%, mean 0.04% -- negligible next
# to survey accuracy).


def esc(val):
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def to_multipolygon(geom):
    if geom.geom_type == "Polygon":
        return MultiPolygon([geom])
    return geom


def main():
    gdf = gpd.read_file(GPKG_PATH)
    gdf = gdf.to_crs("EPSG:4326")
    gdf["geometry"] = shapely.set_precision(
        gdf["geometry"].values, grid_size=PRECISION_GRID, mode="valid_output"
    )
    gdf["geometry"] = gdf["geometry"].apply(to_multipolygon)

    lines = [
        "-- " + "=" * 72,
        "-- geo_landuse: land-use classification polygons (per province)",
        f"-- Source: {GPKG_PATH.rsplit('/', 1)[-1]}, p_code={P_CODE}, EPSG:32647 -> EPSG:4326",
        "-- Generated by postgis/gen_geo_landuse_sql.py -- do not edit by hand",
        "-- " + "=" * 72,
        "",
        "CREATE TABLE public.geo_landuse (",
        "    id SERIAL PRIMARY KEY,",
        "    p_code text NOT NULL,",
        "    lu_year integer NOT NULL,",
        "    lu_code text,",
        "    lu_des_th text,",
        "    lu_des_en text,",
        "    lul1_code text,",
        "    lul2_code text,",
        "    lu_des text,",
        "    geom geometry(MultiPolygon,4326)",
        ");",
        "",
        "INSERT INTO public.geo_landuse",
        "  (p_code, lu_year, lu_code, lu_des_th, lu_des_en, lul1_code, lul2_code, lu_des, geom)",
        "VALUES",
    ]

    rows = []
    for _, r in gdf.iterrows():
        wkt = shapely_wkt.dumps(r.geometry, rounding_precision=COORD_PRECISION)
        geom_sql = f"ST_SetSRID('{wkt}'::geometry, 4326)"
        rows.append(
            f"  ({esc(P_CODE)}, {LU_YEAR}, "
            f"{esc(r['LU_CODE'])}, {esc(r['LU_DES_TH'])}, {esc(r['LU_DES_EN'])}, "
            f"{esc(r['LUL1_CODE'])}, {esc(r['LUL2_CODE'])}, {esc(r['LU_DES'])}, {geom_sql})"
        )
    lines.append(",\n".join(rows) + ";")
    lines.append("")

    lines += [
        "CREATE INDEX geo_landuse_p_code_year_idx ON public.geo_landuse (p_code, lu_year);",
        "CREATE INDEX geo_landuse_geom_idx ON public.geo_landuse USING gist (geom);",
        "",
    ]

    sys.stdout.write("\n".join(lines) + "\n")
    n_vertices = sum(
        sum(len(p.exterior.coords) + sum(len(i.coords) for i in p.interiors) for p in g.geoms)
        for g in gdf["geometry"]
    )
    print(f"-- {len(gdf)} land-use features, {n_vertices} vertices, p_code={P_CODE}", file=sys.stderr)


if __name__ == "__main__":
    main()