-- ============================================================================
-- Migration 002 — geo_thailand: full-resolution province boundaries
-- ============================================================================
-- Run against an EXISTING database (the postgis/init/*.sql scripts only run
-- when the Docker volume is created fresh):
--
--   docker compose exec -T postgis \
--     psql -U keptcarbon -d keptcarbon -v ON_ERROR_STOP=1 \
--     < postgis/migrations/002_geo_thailand.sql
--
-- Purely additive: creates one new table (geo_thailand) and its indexes.
-- Touches no existing table/column, so no maintenance window is required and
-- old application code keeps working untouched until it's redeployed to use
-- the new table.
--
-- Source data lives in postgis/init/06-geo-thailand.sql (same file the fresh-
-- volume bootstrap uses) so the two paths can never drift apart. That file
-- is generated by postgis/gen_geo_thailand_sql.py from TH_PROVINCE.gpkg —
-- see that script's docstring for regeneration instructions.
-- ============================================================================

BEGIN;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'geo_thailand'
  ) THEN
    RAISE EXCEPTION 'geo_thailand already exists -- migration 002 already applied, aborting.';
  END IF;
END $$;

\i /docker-entrypoint-initdb.d/06-geo-thailand.sql

-- Migration summary, printed before commit
DO $$
DECLARE
  n_provinces BIGINT;
BEGIN
  SELECT COUNT(*) INTO n_provinces FROM geo_thailand;
  RAISE NOTICE 'geo_thailand seeded: % provinces', n_provinces;
END $$;

COMMIT;
