-- ============================================================================
-- Migration 004 — geo_landuse: land-use classification polygons (per province)
-- ============================================================================
-- Run against an EXISTING database (the postgis/init/*.sql scripts only run
-- when the Docker volume is created fresh):
--
--   docker compose exec -T postgis \
--     psql -U keptcarbon -d keptcarbon -v ON_ERROR_STOP=1 \
--     < postgis/migrations/004_geo_landuse.sql
--
-- Purely additive: creates one new table (geo_landuse) and its indexes.
-- Touches no existing table/column, so no maintenance window is required.
--
-- Source data lives in postgis/init/12-geo-landuse.sql (same file the fresh-
-- volume bootstrap uses) so the two paths can never drift apart. That file
-- is generated by postgis/gen_geo_landuse_sql.py from LU_RYG_2567.gpkg --
-- see that script's docstring for regeneration instructions (p_code is
-- injected as a constant per source file; only "RAY" exists today).
-- ============================================================================

BEGIN;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'geo_landuse'
  ) THEN
    RAISE EXCEPTION 'geo_landuse already exists -- migration 004 already applied, aborting.';
  END IF;
END $$;

\i /docker-entrypoint-initdb.d/12-geo-landuse.sql

-- Migration summary, printed before commit
DO $$
DECLARE
  n_features BIGINT;
BEGIN
  SELECT COUNT(*) INTO n_features FROM geo_landuse;
  RAISE NOTICE 'geo_landuse seeded: % land-use features', n_features;
END $$;

COMMIT;