-- ============================================================================
-- Migration 008 — tbl_biomass_profile: seed biomass lookup rows
-- ============================================================================
-- Run against an EXISTING database (the postgis/init/*.sql scripts only run
-- when the Docker volume is created fresh):
--
--   docker compose exec -T postgis \
--     psql -U keptcarbon -d keptcarbon -v ON_ERROR_STOP=1 \
--     < postgis/migrations/008_biomass_profile_data.sql
--
-- Purely additive: inserts rows into the existing (empty) tbl_biomass_profile
-- table (created by postgis/init/05-tbl-biomass-profile.sql / an earlier
-- deploy). No maintenance window required.
--
-- Source data lives in postgis/init/14-biomass-profile-data.sql (same file
-- the fresh-volume bootstrap uses) so the two paths can never drift apart.
-- That file is generated by postgis/gen_biomass_profile_sql.py from the CSVs
-- under backend/app/data/lookup_tables/ -- see that script's docstring for
-- regeneration instructions.
--
-- Background: commit a28cab2 replaced CarbonService's flat-CSV lookup with
-- this table and deleted the source CSVs, but never added the load step --
-- this migration (and 007_geo_planting_year.sql, same commit's other
-- half-finished table) fixes that gap.
-- ============================================================================

BEGIN;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM tbl_biomass_profile LIMIT 1) THEN
    RAISE EXCEPTION 'tbl_biomass_profile already has rows -- migration 008 already applied, aborting.';
  END IF;
END $$;

\i /docker-entrypoint-initdb.d/14-biomass-profile-data.sql

DO $$
DECLARE
  n_rows BIGINT;
BEGIN
  SELECT COUNT(*) INTO n_rows FROM tbl_biomass_profile;
  RAISE NOTICE 'tbl_biomass_profile seeded: % rows', n_rows;
END $$;

COMMIT;
